name: quimicapp
description: "Aprende quimica facilmente"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_hooks: ^0.20.5
  provider: ^6.0.1
  charset_converter: ^2.2.0
  lottie: ^3.1.0
  text_neon_widget : ^1.0.5
  neon_widgets: ^2.0.0
  mailer: ^6.1.0
  url_launcher: ^6.2.6
  flutter_pdfview: ^1.3.2
  path_provider: ^2.0.8
  permission_handler: ^11.3.1
  file_picker: ^4.2.0
  assets_audio_player: ^3.0.8
  marquee: ^2.2.3
  flutter_launcher_icons: "^0.9.2"
  another_flushbar: ^1.12.30

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/espectros/
    - assets/audios/
  fonts:
    - family: Futura
      fonts:
        - asset: fonts/futura.otf
    - family: splashScreen
      fonts:
        - asset: fonts/breakingbad.otf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"